# Generated by Django 5.0.4 on 2024-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musician",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="last_name",
        ),
        migrations.AddField(
            model_name="musician",
            name="likes",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=999999999
            ),
            preserve_default=False,
        ),
    ]
