# Generated by Django 5.0.4 on 2024-05-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_rename_first_name_musician_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="song_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="song_file",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="song_lenght",
            new_name="lenght",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="song_name",
            new_name="name",
        ),
    ]
