# Generated by Django 5.0.4 on 2024-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_rename_song_description_song_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.FileField(upload_to="songs"),
        ),
    ]
