# Generated by Django 5.0.4 on 2024-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0004_alter_song_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musician",
            name="likes",
            field=models.DecimalField(decimal_places=0, max_digits=99),
        ),
    ]
