# Generated by Django 5.0.4 on 2024-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0005_alter_musician_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.FileField(upload_to="media/"),
        ),
    ]
