# Generated by Django 5.0.4 on 2024-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0006_alter_song_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="lenght",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
