# Generated by Django 5.0.4 on 2024-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0008_playlist_playlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="list",
            field=models.ManyToManyField(to="player.song"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name="PlaylistItem",
        ),
    ]
