# Generated by Django 5.0.4 on 2024-05-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0009_playlist_list_alter_playlist_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="list",
        ),
        migrations.AddField(
            model_name="playlist",
            name="list",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.song",
            ),
        ),
    ]
