# Generated by Django 5.0.4 on 2024-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0011_remove_playlist_list_playlist_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="cover",
            field=models.FileField(blank=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="list",
            field=models.ManyToManyField(blank=True, to="player.song"),
        ),
    ]
