# Generated by Django 5.0.4 on 2024-05-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0012_playlist_cover_alter_playlist_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="lenght",
        ),
    ]
